version: '3'

services:
  web:
    build: . #path
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 #commands
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgresnnn
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test123
    container_name: postgres_db

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: pgadmin