version: '3'

services:
  web:
    build: . #path
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 #commands
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test123
    container_name: postgres_db